# Dataset
DATASET = "dataset/chessData.csv" 
N_ROWS = 100_000

# NN architecture
N_FEATURES = 8*8*12
HIDDEN_ACTIVATION = "relu"
OUTPUT_ACTIVATION = "relu"

# Training
LEARNING_RATE = 0.0001
REGULARIZATION_RATE = 0
EPOCHS = 30
BATCH_SIZE = 32
PATIENCE = 3
